language: php

php:
    - 7.2
    - 7.4

cache:
    directories:
        - $HOME/.composer/cache

env:
    global:
        - APPLICATION_ENV=development
        - APPLICATION_STORE=DE

before_install:
    - if [[ ${TRAVIS_PHP_VERSION} != "7.4" ]]; then phpenv config-rm xdebug.ini ; fi

before_script:
    - COMPOSER_MEMORY_LIMIT=-1 composer install --prefer-dist --no-interaction

script:
    - composer cs-check

notifications:
    email: false
