language: php

php:
    - 7.1
    - 7.3

cache:
    directories:
        - vendor
        - $HOME/.composer/cache

env:
    global:
        - APPLICATION_ENV=development
        - APPLICATION_STORE=DE

before_install:
    - echo "memory_limit = -1" >> travis.ini
    - phpenv config-add travis.ini

install:
    - composer update --no-interaction --prefer-dist

script:
    - vendor/bin/phpcs src --standard=vendor/spryker/code-sniffer/Spryker/ruleset.xml
    - vendor/bin/phpcs tests --standard=vendor/spryker/code-sniffer/Spryker/ruleset.xml

after_success:
    - vendor/bin/coveralls -vvv

notifications:
    email: false
